services:
  api:
    container_name: api
    build:
      context: ../
      target: development # or "production"
    env_file: .env
    ports:
      - ${API_PORT}:3000
      - 9229:9229 # vscode debug port
    networks:
      - db-network
      - app-network
    volumes:
      - ../modules:/app/src/extra
      - ../extensions:/app/src/.hexabot/custom/extensions
      - api-data:/app/uploads
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: "wget --spider http://localhost:3000"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  ui:
    container_name: ui
    image: hexastack/hexabot-ui:latest
    env_file: .env
    ports:
      - ${APP_FRONTEND_PORT}:8080
    networks:
      - app-network
    depends_on:
      api:
        condition: service_healthy

  mongo:
    container_name: mongo
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - db-network
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - mongo-data:/data/db

  ollama:
    container_name: ollama
    image: sha256:325786c469dadaa0abfad3acdef17f684e7f159ca27ecd43b1851c8aec97ffc4
    ports:
      - "11434:11434" # Adjust this port if necessary
    networks:
      - ollama-network
    restart: unless-stopped

  nlu-api:
    container_name: nlu-api
    image: hexastack/hexabot-nlu:latest
    env_file: .env
    ports:
      - ${NLU_PORT}:5000
    networks:
      - app-network
      - nlu-network
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  mongo-data:
  api-data:

networks:
  db-network:
  app-network:
  ollama-network:
    driver: bridge
  nlu-network:
    driver: bridge
